from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


MANIFEST_FILENAME = "generated-manifest.json"
GENERATED_BANNER = "<!-- Generated by scripts/export_from_paper.py. Do not edit by hand. -->\n\n"
TOKEN_OUTPUTS = {
    "design/tokens/colors.json",
    "design/tokens/typography.json",
    "design/tokens/tokens.css",
}


def generated_kind(path: Path) -> str:
    suffix = path.suffix.lower()
    if suffix == ".html":
        return "html"
    if suffix == ".md":
        return "markdown"
    if suffix == ".png":
        return "png"
    if suffix == ".json":
        return "json"
    if suffix == ".css":
        return "css"
    return "asset"


def add_generated_banner(path: Path, content: str) -> str:
    if path.suffix.lower() not in {".html", ".md"}:
        return content
    if content.startswith(GENERATED_BANNER):
        return content
    return GENERATED_BANNER + content


def is_generated_path(repo_root: Path, path: Path) -> bool:
    rel = path.relative_to(repo_root).as_posix()
    name = path.name
    if rel in TOKEN_OUTPUTS:
        return True
    if rel.startswith("assets/paper/") and path.is_file():
        return True
    if rel.startswith("screens/_shared/") and path.suffix == ".html":
        return True
    if rel.startswith("screens/") and name in {"README.md", "screen.html", "screenshot.png"}:
        return True
    if rel.startswith("design/glossary/") and (
        name == "README.md" or name.endswith(".md") or name.endswith("-screenshot.png")
    ):
        return True
    if rel.startswith("design/") and name in {"README.md", "reference.html", "screenshot.png"}:
        return True
    return False


def collect_generated_files(repo_root: Path) -> list[Path]:
    roots = [repo_root / "design", repo_root / "screens", repo_root / "assets" / "paper"]
    files: list[Path] = []
    for root in roots:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if path.is_file() and is_generated_path(repo_root, path):
                files.append(path)
    return sorted(files, key=lambda path: path.relative_to(repo_root).as_posix())


def manifest_path(repo_root: Path) -> Path:
    return repo_root / MANIFEST_FILENAME


def manifest_data(repo_root: Path, files: list[Path] | None = None) -> dict[str, Any]:
    generated = files if files is not None else collect_generated_files(repo_root)
    return {
        "version": 1,
        "generatedAt": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "files": [
            {
                "path": path.relative_to(repo_root).as_posix(),
                "kind": generated_kind(path),
            }
            for path in generated
        ],
    }


def write_manifest(repo_root: Path) -> None:
    path = manifest_path(repo_root)
    path.write_text(json.dumps(manifest_data(repo_root), indent=2) + "\n")
